### ISSUE TITLE
Extra carets on selects

### ISSUE THREAD

**Issue by serkandurusoy** [djhi/meteor-autoform-materialize#64]
While using material selects,
- especially those whose options are computed,
- or change depending on some other field's value, 
- lots of carets appear the parent div of the select

Prior to 0.0.24, I used the following workaround in my schema definition:

``` javascript
fieldOne: {
  type: String,
  autoform: {
    firstOption: 'Select an option',
    options: function() {
      var optionsObject = someFunctionOrExpressionThatBuildsTheOptionsObject();
      var $this = $('[name="fieldOne"]');
      $this.parent().find('span.caret').remove();
      $this.material_select();
      return optionObject;
    }
  }
}
```

This has been a [known problem](https://github.com/Dogfalo/materialize/issues?q=is%3Aissue+caret+is%3Aclosed) and the above a suggested workaround.

**BUT**

As of 0.0.24 this does not work. Namely, an additional caret appears above the select no matter what. To mitigate that, I run the cleanup twice like below:

``` javascript
fieldOne: {
  type: String,
  autoform: {
    firstOption: 'Select an option',
    options: function() {
      var optionsObject = someFunctionOrExpressionThatBuildsTheOptionsObject();
      var $this = $('[name="fieldOne"]');
      $this.parent().find('span.caret').remove();
      $this.material_select();
      $this.parent().find('span.caret').remove();
      return optionObject;
    }
  }
}
```

_BUT_ this works only for the first render of the autoform. If the options get updated due to some reactive update, another single extra caret appears above.

Now I know this is more of a materializecss bug, but still the suggested workaround used to do fine until whatever caused it to stop working with the 0.0.24 release.

**Comment by boustanihani** [comment]
Same issue here (after upgrading to 0.0.24)

**Comment by djhi** [comment]
Probably related to #58.

I noticed the bug as stated in the comment but I can't figure out how to fix it.

**Comment by serkandurusoy** [comment]
Hmm, is it possible that the debounce is causing the final extra caret?

Instead of debouncing, you could use `afterflush` perhaps or `defer`?

**Comment by 0o-de-lally** [comment]
Any ideas for a quick fix?

This is what I am seeing with:
gildaspk:autoform-materialize  0.0.24
materialize:materialize        0.97.0

![screenshot 2015-09-02 19 53 08](https://cloud.githubusercontent.com/assets/1364012/9647566/6ef629be-51ac-11e5-81e3-3597605fa2fa.png)

**Comment by serkandurusoy** [comment]
I ditched material_select for the browser-select and added some custom styles to make it look like material select.

add this to your schema key:

``` javascript
autoform : {
  class: 'browser-default'
}
```

and in your css

``` css
select.browser-default {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  background: none;
  padding-left: 0;
  text-indent: 0;
  border: none;
  border-bottom: 1px solid #9e9e9e;
  margin-bottom: 15px;
}

select.browser-default option {
  padding-left: 0;
  text-indent: 0;
}

select.browser-default+label {
  transform: translateY(-140%);
  font-size: 0.8rem;
}

select.browser-default:focus {
  outline: none;
  border-bottom: 1px solid #26a69a;
  box-shadow: 0 1px 0 0 #26a69a;
}

select.browser-default option:focus {
  outline: none;
}

select.browser-default:focus+label {
  color: #26a69a;
}
```
