### ISSUE TITLE
Select-checkbox broken after 0.0.24 release

### ISSUE THREAD

**Issue by serkandurusoy** [djhi/meteor-autoform-materialize#65]
Select-checkboxes that are generated from [String] schema type now have incorrect `id` in the form of `XXXXXXXXXXX_undefined` sharing the same id for all options, therefore multiple options can no longer be selected.

Therefore, select-checkbox type is now rendered useless.

Before this update, such problem did not exist.

**Comment by serkandurusoy** [comment]
https://github.com/djhi/meteor-autoform-materialize/blob/master/utilities/helpers/item-atts-with-uniq-id.js#L4

`this._id` returns `undefined` here

version 0.0.23 used to return the option value itself for this._id

**Comment by Chun-Yang** [comment]
@serkandurusoy I think the new version fixed this problem. Can you confirm? Thank you!

**Comment by serkandurusoy** [comment]
Nope, unfortunately this did not fix the checkbox problem, checkboxes still unchecked updating with quickform

**Comment by serkandurusoy** [comment]
My bad, I hadn't upgraded.

It is resolved, thanks!

But there is a slight visual problem. The last checkbox gets cut in the middle because it overflows its container. I added the following css to mitigate it temporarily:

``` css
// TODO: check if this messes up with other form elements
form p:last-child {
  margin-bottom: inherit !important;
}

form p:first-child {
  margin-top: 0 !important;
}
```
