### ISSUE TITLE
How to enable selectYears for pickadate?

### ISSUE THREAD

**Issue by JulianKingman** [djhi/meteor-autoform-materialize#71]
If you look at the date picker on the Materialize website (http://materializecss.com/forms.html#date-picker), it allows you to select years. How can I enable this in this autoform, within the schema? For putting my birthday into a form I have to click the little arrow hundreds of times :s

Something like `selectYears: true` would be great.

**Comment by kozy** [comment]
I had the same question. The following autoform configuration works (coffee script)

```
autoform:
  type: 'pickadate'
  pickadateOptions:
    selectYears: true
    selectMonths: true
```
